# Generated by Django 5.2.6 on 2025-10-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(default='profile_default..jpg', upload_to='profile_pictures.jpg')),
            ],
        ),
    ]
