# Generated by Django 5.2.6 on 2025-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
